const data = {
  products: [
    {
      name: "Bitcoin Shirt 1",
      slug: "bitcoin-shirt-1",
      category: "Shirts",
      image: "/images/shirt1.png",
      price: 70000,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "An amazing Bitcoin Shirt",
    },
    {
      name: "Bitcoin Shirt 2",
      slug: "bitcoin-shirt-2",
      category: "Shirts",
      image: "/images/shirt2.png",
      price: 80000,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "An amazing Bitcoin Shirt",
    },
    {
      name: "Bitcoin Shirt 3",
      slug: "bitcoin-shirt-3",
      category: "Shirts",
      image: "/images/shirt3.png",
      price: 90000,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "An amazing Bitcoin Shirt",
    },
    {
      name: "Bitcoin Shirt 4",
      slug: "bitcoin-shirt-4",
      category: "Shirts",
      image: "/images/shirt4.png",
      price: 100000,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "An amazing Bitcoin Shirt",
    },
    {
      name: "Bitcoin Shirt 5",
      slug: "bitcoin-shirt-5",
      category: "Shirts",
      image: "/images/shirt5.png",
      price: 75000,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "An amazing Bitcoin Shirt",
    },
    {
      name: "Bitcoin Shirt 6",
      slug: "bitcoin-shirt-6",
      category: "Shirts",
      image: "/images/shirt6.png",
      price: 85000,
      brand: "Aldo",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "An amazing Bitcoin Shirt",
    },
    {
      name: "Bitcoin Shirt 7",
      slug: "bitcoin-shirt-7",
      category: "Shirts",
      image: "/images/shirt7.png",
      price: 95000,
      brand: "3 Second",
      rating: 4,
      numReviews: 10,
      countInStock: 20,
      description: "An amazing Bitcoin Shirt",
    },
    {
      name: "Bitcoin Shirt 8",
      slug: "bitcoin-shirt-8",
      category: "Shirts",
      image: "/images/shirt8.png",
      price: 105000,
      brand: "Nike",
      rating: 3,
      numReviews: 10,
      countInStock: 20,
      description: "An amazing Bitcoin Shirt",
    },
    {
      name: "Bitcoin Shirt 9",
      slug: "bitcoin-shirt-9",
      category: "Shirts",
      image: "/images/shirt9.png",
      price: 115000,
      brand: "Supreme",
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: "An amazing Bitcoin Shirt",
    },
  ]
}

export default data